version: '3'
services:
    mono:
        build:
            context: ./
            dockerfile: ./mono.dockerfile
        environment:
            DISPLAY: '10.0.0.4:0'
        volumes:    
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
            - '.:/root/lab0'
